#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr  5 13:13:20 2017

@author: patrizio
"""

class yeld_data:
    def __init__(self):
        self.a = [1,2,3,4,5]

    def yeld(self):
        for i in self.a:
            yield i
        
if __name__ == '__main__':
    b = yeld_data()
#    
#    while True:
#        print (b.yeld())
for i in b.yeld():
    print (i)